import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Noto_Sans_Thai } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";


const micro5 = localFont({
  src: [
    {
      path: "./font/Micro5-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-micro5", 
});

const notoSansThai = Noto_Sans_Thai({
  subsets: ["thai"],
  weight: ["400", "700"],
  display: "swap",
  variable: "--font-thai",
});

const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="th">
      <body
        className={`${notoSansThai.variable} ${geistSans.variable} ${geistMono.variable} ${micro5.variable} font-thai`}
      >
        {children}
      </body>
    </html>
  );
}
